# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19koUB5MUB4a_BR57fpQSQRgMs-CxNUj1
"""

# train_pathvqa_lora.py

import torch
from datasets import load_dataset
from unsloth import FastVisionModel
from unsloth.trainer import UnslothVisionDataCollator
from trl import SFTTrainer, SFTConfig


MODEL_NAME = "unsloth/Qwen3.5-2B"
RANK = 64
TOP_K = 2000
SEED = 3407
OUTPUT_DIR = f"outputs_{RANK}"
SAVE_DIR = f"qwen_lora_rank_{RANK}"


def convert_to_conversation(sample):
    instruction = sample["question"]
    return {
        "messages": [
            {
                "role": "user",
                "content": [
                    {"type": "text", "text": instruction},
                    {"type": "image", "image": sample["image"].convert("RGB")},
                ],
            },
            {
                "role": "assistant",
                "content": [
                    {"type": "text", "text": sample["answer"]},
                ],
            },
        ]
    }


def main():
    print("Loading model...")
    model, tokenizer = FastVisionModel.from_pretrained(
        MODEL_NAME,
        load_in_4bit=False,
        use_gradient_checkpointing="unsloth",
    )

    model = FastVisionModel.get_peft_model(
        model,
        finetune_vision_layers=True,
        finetune_language_layers=True,
        finetune_attention_modules=True,
        finetune_mlp_modules=True,
        r=RANK,
        lora_alpha=RANK * 2,
        lora_dropout=0,
        bias="none",
        random_state=SEED,
        use_rslora=False,
        loftq_config=None,
    )

    print("Loading PathVQA dataset...")
    dataset = load_dataset("flaviagiammarino/path-vqa", split="train")
    dataset = dataset.select(range(TOP_K))
    dataset = dataset.train_test_split(test_size=0.1, seed=SEED)

    train_dataset = dataset["train"]
    eval_dataset = dataset["test"]

    converted_train_dataset = [convert_to_conversation(sample) for sample in train_dataset]
    converted_eval_dataset = [convert_to_conversation(sample) for sample in eval_dataset]

    print(f"Training set size: {len(converted_train_dataset)}")
    print(f"Validation set size: {len(converted_eval_dataset)}")

    FastVisionModel.for_training(model)

    trainer = SFTTrainer(
        model=model,
        tokenizer=tokenizer,
        data_collator=UnslothVisionDataCollator(model, tokenizer),
        train_dataset=converted_train_dataset,
        eval_dataset=converted_eval_dataset,
        args=SFTConfig(
            per_device_train_batch_size=8,
            per_device_eval_batch_size=8,
            gradient_accumulation_steps=1,
            num_train_epochs=1,
            learning_rate=2e-4,
            warmup_steps=5,
            lr_scheduler_type="linear",
            logging_steps=10,
            eval_strategy="steps",
            eval_steps=100,
            optim="adamw_8bit",
            weight_decay=0.001,
            seed=SEED,
            output_dir=OUTPUT_DIR,
            report_to="none",
            remove_unused_columns=False,
            dataset_text_field="",
            disable_tqdm=True,
            dataset_kwargs={"skip_prepare_dataset": True},
            max_length=2048,
        ),
    )

    trainer_stats = trainer.train()

    model.save_pretrained(SAVE_DIR)
    tokenizer.save_pretrained(SAVE_DIR)

    print(f"Training completed! Total time: {round(trainer_stats.metrics['train_runtime']/60, 2)} minutes.")


if __name__ == "__main__":
    main()